name: basic_interfaces
description: A tiny collection of basic interfaces.
version: 1.0.0
repository: https://github.com/jinyus/dart_basic_interfaces

environment:
    sdk: "^3.0.0"

dependencies:
    meta: ^1.12.0
